import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import FrameBorder from "@/components/layout/FrameBorder";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// スクロールバーを非表示にするためのクラス
const noScrollbar = "no-scrollbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={noScrollbar} suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} no-scrollbar antialiased`}
      >
        <FrameBorder></FrameBorder>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
