/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/fini.glb -t
*/

// サブスタでpcとmonitorとdeskのlight書き込む
// ガラスと分離して、pcとmonitorはアルファテクスチャで透過させる
// スマホ表記を直す

import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { useMemo, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";
import { useRoomAnimation } from "@/components/useRoomAnimation";
import { DigitalClock } from "@/components/DigitalClock";
import { MusicParticles } from "@/components/MusicParticles";
import { MonitorContent } from "@/components/MonitorSystem";

interface Props {
  isDark?: boolean;
}

type GLTFAction = THREE.AnimationClip;

type GLTFResult = GLTF & {
  nodes: {
    runba: THREE.Mesh;
    pc: THREE.Mesh;
    monitor_center: THREE.Mesh;
    monitor_right: THREE.Mesh;
    mic: THREE.Mesh;
    shelf: THREE.Mesh;
    chiar: THREE.Mesh;
    clock: THREE.Mesh;
    mirror: THREE.Mesh;
    desk_small: THREE.Mesh;
    cushions_1: THREE.Mesh;
    cushions_2: THREE.Mesh;
    floor: THREE.Mesh;
    mat1: THREE.Mesh;
    mat2: THREE.Mesh;
    rimo: THREE.Mesh;
    light: THREE.Mesh;
    music: THREE.Mesh;
    musicOFF: THREE.Mesh;
    musicON: THREE.Mesh;
    bed: THREE.Mesh;
    bed_Dark: THREE.Mesh;
    bed_Light: THREE.Mesh;
    desk_big: THREE.Mesh;
    cup_Light: THREE.Mesh;
    juce_Dark: THREE.Mesh;
  };
  materials: {
    Mat_All: THREE.MeshStandardMaterial; // 使わないので無視してOK
  };
  animations: GLTFAction[];
};

// 【重要】Dracoのデコーダーは解凍に必須なので絶対に消さない！
useGLTF.setDecoderPath(
  "https://www.gstatic.com/draco/versioned/decoders/1.5.5/"
);

export function Model({ isDark, ...props }: Props & ThreeElements["group"]) {
  const { nodes } = useGLTF("/fini.glb") as unknown as GLTFResult;

  const roomRef = useRef<THREE.Group>(null);
  useRoomAnimation(roomRef);

  const turnOnTexture = useTexture("/TurnOn_BaseColor.webp");
  const turnOffTexture = useTexture("/TurnOff_BaseColor.webp");

  const rawTexture = isDark ? turnOffTexture : turnOnTexture;

  const bakedTexture = useMemo(() => {
    if (!rawTexture) return null;
    const t = rawTexture.clone();
    t.flipY = false;

    t.colorSpace = THREE.SRGBColorSpace;

    t.anisotropy = 2;
    t.minFilter = THREE.LinearFilter;
    t.magFilter = THREE.LinearFilter;
    t.needsUpdate = true;
    return t;
  }, [rawTexture]);

  return (
    <group ref={roomRef} {...props} dispose={null}>
      {/* ===== 床・ラグ系 ===== */}
      <mesh geometry={nodes.floor.geometry} position={[0.607, -0.068, 0.076]}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh geometry={nodes.mat1.geometry} position={[1.498, 0, 0.505]}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh geometry={nodes.mat2.geometry} position={[-0.822, 0.004, 0.297]}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>

      {/* ===== メインデスク周り ===== */}
      <mesh
        geometry={nodes.desk_big.geometry}
        position={[-1.284, 0.951, 0.453]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh geometry={nodes.chiar.geometry} position={[-0.615, 0.475, 0.483]}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>

      {/* メインモニター (SpotLightとコンテンツ入り) */}
      <mesh
        geometry={nodes.monitor_center.geometry}
        position={[-1.363, 1.255, 0.477]}
        rotation={[0.002, -0.003, 0.069]}
      >
        <meshBasicMaterial map={bakedTexture} />
        <group
          position={[0, 0, 0]}
          rotation-order="YXZ"
          rotation={[0, Math.PI / 2 - 0.003, 0]}
        >
          <MonitorContent monitorId={0} width={0.61} height={0.36} />
        </group>
        <spotLight
          position={[0.02, 0.085, 0]}
          shadow-bias={-0.0001}
          intensity={isDark ? 0.5 : 0}
          angle={Math.PI / 2}
          penumbra={0.2}
          distance={0.4}
          color="#d5d5d5"
          onUpdate={(self) => {
            self.target.position.set(0.12, 0.185, 0);
            self.target.updateMatrixWorld();
          }}
        />
      </mesh>

      {/* サブモニター (SpotLightとコンテンツ入り) */}
      <mesh
        geometry={nodes.monitor_right.geometry}
        position={[-1.186, 1.255, -0.163]}
        rotation={[0.002, -0.49, 0.07]}
      >
        <meshBasicMaterial map={bakedTexture} />
        <group position={[0, 0, 0]} rotation={[0, Math.PI / 2, 0]}>
          <MonitorContent monitorId={1} width={0.61} height={0.36} />
        </group>
        <spotLight
          position={[0.027, 0.08, 0]}
          shadow-bias={-0.0001}
          intensity={isDark ? 0.5 : 0}
          angle={Math.PI / 2}
          penumbra={0.2}
          distance={0.4}
          color="#d5d5d5"
          onUpdate={(self) => {
            self.target.position.set(0.077, 0.08, 0);
            self.target.updateMatrixWorld();
          }}
        />
      </mesh>

      {/* PC本体・マイク */}
      <mesh
        geometry={nodes.pc.geometry}
        position={[-1.244, 0.258, -0.629]}
        rotation={[0, -Math.PI / 2, 0]}
      >
        <meshBasicMaterial
          map={bakedTexture}
          transparent={true}
          depthWrite={false}
          alphaTest={0.5}
        />
        {/* PC内部用のライトを再設定 */}
        <pointLight intensity={isDark ? 0.2 : 0} distance={0.3} decay={2} />
      </mesh>
      <mesh geometry={nodes.mic.geometry} position={[-1.35, 1.122, 0.907]}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>

      {/* 時計 (DigitalClockとSpotLight入り) */}
      <mesh
        geometry={nodes.clock.geometry}
        position={[-1.425, 1.048, 1.174]}
        rotation={[0, 1.57, 0]}
      >
        <meshBasicMaterial map={bakedTexture} />
        <DigitalClock />
        <mesh position={[0, 0, 0.0505]}>
          <planeGeometry args={[0.23, 0.12]} />
          <meshBasicMaterial color="#c0c0c0" />
        </mesh>
        <spotLight
          position={[0, 0, 0]}
          shadow-bias={-0.0001}
          intensity={isDark ? 0.1 : 0}
          angle={Math.PI / 2}
          penumbra={0.5}
          distance={0.2}
          color="#d5d5d5"
          onUpdate={(self) => {
            self.target.position.set(1, 0, 0.0505);
            self.target.updateMatrixWorld();
          }}
        />
      </mesh>

      {/* 飲み物（Dark / Lightで出し分け） */}
      <mesh
        geometry={nodes.juce_Dark.geometry}
        position={[-1.157, 1.067, 1.222]}
        visible={isDark}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        geometry={nodes.cup_Light.geometry}
        position={[-1.158, 1.04, 1.138]}
        visible={!isDark}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>

      {/* ===== 部屋の小物・家具 ===== */}
      <mesh geometry={nodes.shelf.geometry} position={[0.456, 0.54, -1.189]}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        geometry={nodes.mirror.geometry}
        position={[-1.033, 0.879, -1.167]}
        rotation={[-0.393, 0.887, -2.831]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh geometry={nodes.runba.geometry} position={[-0.172, 0.029, -1.155]}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>

      {/* レコード・音楽系（Darkで出し分け＆パーティクル） */}
      <mesh
        geometry={nodes.music.geometry}
        position={[0.461, 1.119, -1.174]}
        rotation={[0, -Math.PI / 2, 0]}
      >
        <meshBasicMaterial map={bakedTexture} />
        <group visible={!isDark}>
          <MusicParticles />
        </group>
      </mesh>
      <mesh
        geometry={nodes.musicON.geometry}
        position={[0.475, 1.15, -1.161]}
        rotation={[0, -0.667, 0]}
        visible={isDark}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        geometry={nodes.musicOFF.geometry}
        position={[0.567, 1.144, -1.108]}
        visible={!isDark}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>

      {/* ===== ベッド周り ===== */}
      <mesh geometry={nodes.bed.geometry} position={[1.799, 0.492, -0.819]}>
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        geometry={nodes.bed_Dark.geometry}
        position={[1.885, 0.735, -0.827]}
        visible={isDark}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        geometry={nodes.bed_Light.geometry}
        position={[1.885, 0.735, -0.827]}
        visible={!isDark}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        geometry={nodes.cushions_1.geometry}
        position={[2.053, -0.028, 0.519]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        geometry={nodes.cushions_2.geometry}
        position={[2.069, 0.132, 0.804]}
        rotation={[0.521, 0.166, 0.015]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>

      {/* ===== ミニデスク周り ===== */}
      <mesh
        geometry={nodes.desk_small.geometry}
        position={[1.138, 0.309, 0.632]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>

      {/* ミニデスク用ライト (SpotLight入り) */}
      <mesh geometry={nodes.light.geometry} position={[0.918, 0.347, 0.427]}>
        <meshBasicMaterial map={bakedTexture} />
        <spotLight
          position={[0, -0.079, 0]}
          shadow-bias={-0.0001}
          intensity={isDark ? 1 : 0}
          angle={Math.PI / 3}
          penumbra={0.2}
          distance={0.4}
          color="#d5d5d5"
          onUpdate={(self) => {
            self.target.position.set(1.137, 0.229, 0.642);
            self.target.updateMatrixWorld();
          }}
        />
      </mesh>

      {/* リモコン (発光パネル入り) */}
      <mesh
        geometry={nodes.rimo.geometry}
        position={[1.188, 0.344, 0.784]}
        rotation={[0, 1.031, 0]}
      >
        <meshBasicMaterial map={bakedTexture} />
        <mesh position={[0, 0.002, -0.035]} rotation={[-Math.PI / 2, 0, 0]}>
          <planeGeometry args={[0.05, 0.035]} />
          <meshBasicMaterial color="#c0c0c0" />
        </mesh>
      </mesh>
    </group>
  );
}

useGLTF.preload("/fini.glb");
