/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Room.glb --types
*/

import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { useMemo, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";
import { useRoomAnimation } from "@/components/useRoomAnimation";
import { DigitalClock } from "@/components/DigitalClock";
import { MusicParticles } from "@/components/MusicParticles";
import { MonitorContent } from "@/components/MonitorSystem";

interface Props {
  isDark?: boolean;
}

type GLTFAction = THREE.AnimationClip;

type GLTFResult = GLTF & {
  nodes: {
    円柱028: THREE.Mesh;
    円柱028_1: THREE.Mesh;
    円柱028_2: THREE.Mesh;
    desk: THREE.Mesh;
    立方体016: THREE.Mesh;
    立方体016_1: THREE.Mesh;
    立方体016_2: THREE.Mesh;
    立方体049: THREE.Mesh;
    立方体049_1: THREE.Mesh;
    立方体049_2: THREE.Mesh;
    円柱004: THREE.Mesh;
    円柱004_1: THREE.Mesh;
    立方体046: THREE.Mesh;
    立方体046_1: THREE.Mesh;
    立方体046_2: THREE.Mesh;
    立方体024: THREE.Mesh;
    立方体024_1: THREE.Mesh;
    立方体024_2: THREE.Mesh;
    円柱018: THREE.Mesh;
    円柱018_1: THREE.Mesh;
    立方体036: THREE.Mesh;
    立方体036_1: THREE.Mesh;
    desk2: THREE.Mesh;
    円柱011: THREE.Mesh;
    円柱011_1: THREE.Mesh;
    立方体019: THREE.Mesh;
    立方体019_1: THREE.Mesh;
    立方体019_2: THREE.Mesh;
    立方体019_3: THREE.Mesh;
    立方体007: THREE.Mesh;
    立方体007_1: THREE.Mesh;
    立方体007_2: THREE.Mesh;
    立方体007_3: THREE.Mesh;
    立方体007_4: THREE.Mesh;
    立方体007_5: THREE.Mesh;
    立方体007_6: THREE.Mesh;
    立方体007_7: THREE.Mesh;
    立方体007_8: THREE.Mesh;
    pc_glass: THREE.Mesh;
    円柱019: THREE.Mesh;
    円柱019_1: THREE.Mesh;
    円柱019_2: THREE.Mesh;
    円004: THREE.Mesh;
    円004_1: THREE.Mesh;
    円004_2: THREE.Mesh;
    円002: THREE.Mesh;
    円002_1: THREE.Mesh;
    円002_2: THREE.Mesh;
    立方体058: THREE.Mesh;
    立方体058_1: THREE.Mesh;
    立方体058_2: THREE.Mesh;
    bedOn: THREE.Mesh;
    bedOff: THREE.Mesh;
    立方体059: THREE.Mesh;
    立方体059_1: THREE.Mesh;
    立方体059_2: THREE.Mesh;
    立方体059_3: THREE.Mesh;
    立方体059_4: THREE.Mesh;
    立方体034: THREE.Mesh;
    立方体034_1: THREE.Mesh;
    立方体055: THREE.Mesh;
    立方体055_1: THREE.Mesh;
    cushion1: THREE.Mesh;
    cushion2: THREE.Mesh;
    pazzle: THREE.Mesh;
    carpet1: THREE.Mesh;
    carpet2: THREE.Mesh;
  };
  materials: {
    [key: string]: THREE.Material;
  };
  animations: GLTFAction[];
};

useGLTF.setDecoderPath(
  "https://www.gstatic.com/draco/versioned/decoders/1.5.5/"
);

export function Model({ isDark, ...props }: Props & ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/Room-draco.glb"
  ) as unknown as GLTFResult;

  const roomRef = useRef<THREE.Group>(null);
  useRoomAnimation(roomRef);

  const rawTexture = useTexture("/PC_Bake.webp");

  const pcTexture = useMemo(() => {
    if (!rawTexture) return null;
    const t = rawTexture.clone();
    t.flipY = false;
    t.anisotropy = 4;
    t.minFilter = THREE.LinearFilter;
    t.magFilter = THREE.LinearFilter;
    t.needsUpdate = true;
    return t;
  }, [rawTexture]);

  return (
    <group ref={roomRef} {...props} dispose={null}>
      {/* puzzle */}
      <group position={[0.5, 0, 0.2]} name="puzzle">
        <mesh
          geometry={nodes.pazzle.geometry}
          material={materials["light blue"]}
          position={[-1.94, 0, 1.105]}
        />
      </group>
      {/* rectangle_carpet_gray */}
      <mesh
        geometry={nodes.carpet2.geometry}
        material={materials.silber}
        position={[-0.822, 0.015, 0.297]}
      />
      {/* chair */}
      <group position={[-0.466, 0.484, 0.343]}>
        <mesh geometry={nodes.立方体034.geometry} material={materials.brown} />
        <mesh
          geometry={nodes.立方体034_1.geometry}
          material={materials["light blue"]}
        />
      </group>
      {/* long_desk */}
      <mesh
        geometry={nodes.desk2.geometry}
        material={materials.brown}
        position={[-1.264, 0.731, 0.474]}
      />
      {/* clock */}
      <group position={[-1.425, 1.046, 1.174]} rotation={[0, 1.57, 0]}>
        <mesh
          geometry={nodes.立方体036.geometry}
          material={materials["light blue"]}
        />
        <mesh
          geometry={nodes.立方体036_1.geometry}
          material={materials.white}
        />
        {/* 時計の文字盤の位置に配置 */}
        <DigitalClock />
        {/* 発光パネル（平面） */}
        <mesh position={[0, 0, 0.0505]}>
          <planeGeometry args={[0.23, 0.12]} />
          <meshStandardMaterial
            color="#c0c0c0"
            emissive={"#cbcbcb"}
            emissiveIntensity={3}
            transparent
          />
        </mesh>
        <spotLight
          position={[0, 0, 0]} // ライトの出どころ
          shadow-bias={-0.0001} // シャドウのアーティファクトを防止
          intensity={isDark ? 0.1 : 0} // 明るさ
          angle={Math.PI / 2} // ライトの広がり具合
          penumbra={0.5} // ライトの中心から縁への減衰具合
          distance={0.2} // ライトの届く距離
          color="#d5d5d5"
          onUpdate={(self) => {
            self.target.position.set(1, 0, 0.0505); // 照らしたい座標（机）
            self.target.updateMatrixWorld(); // 向きを即座に計算
          }}
        />
      </group>
      {/* can1 */}
      <group
        position={[-1.158, 1.074, 1.223]}
        rotation={[-0.332, 0, Math.PI]}
        visible={isDark}
      >
        <mesh
          geometry={nodes.立方体046.geometry}
          material={nodes.立方体046.material}
        />
        <mesh
          geometry={nodes.立方体046_1.geometry}
          material={materials.silber}
        />
        <mesh
          geometry={nodes.立方体046_2.geometry}
          material={materials.orange}
        />
      </group>
      {/* can2 */}
      <group
        position={[-1.225, 1.074, 1.119]}
        rotation={[-0.404, -0.594, 2.907]}
        visible={isDark}
      >
        <mesh
          geometry={nodes.立方体024.geometry}
          material={nodes.立方体024.material}
        />
        <mesh
          geometry={nodes.立方体024_1.geometry}
          material={materials.silber}
        />
        <mesh
          geometry={nodes.立方体024_2.geometry}
          material={materials.orange}
        />
      </group>
      {/* cap */}
      <group position={[-1.158, 1.036, 1.138]} visible={!isDark}>
        <mesh geometry={nodes.円柱018.geometry} material={materials.orange} />
        <mesh geometry={nodes.円柱018_1.geometry} material={materials.white} />
      </group>
      {/* mike */}
      <group
        position={[-1.314, 1.064, 0.907]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh geometry={nodes.円柱004.geometry} material={materials.black} />
        <mesh geometry={nodes.円柱004_1.geometry} material={materials.white} />
      </group>
      {/* main_monitor */}
      <group position={[-1.4, 1.174, 0.477]}>
        <mesh
          geometry={nodes.立方体016.geometry}
          material={materials["light blue"]}
        />
        <mesh
          geometry={nodes.立方体016_1.geometry}
          material={materials.white}
        />
        <mesh
          geometry={nodes.立方体016_2.geometry}
          material={materials.silber}
        />
        <group
          position={[0.02, 0.085, 0]} // 1. まずは表面に出るまで座標をずらす
          rotation-order="YXZ"
          rotation={[-0.07, Math.PI / 2 - 0.003, 0]} // 2. 90度単位で回して正面に向ける
        >
          <MonitorContent
            monitorId={0}
            width={0.61} // 3. 赤い板が左右にはみ出ないかチェック
            height={0.36} // 4. 赤い板が上下にはみ出ないかチェック
          />
        </group>
        <spotLight
          position={[0.02, 0.085, 0]} // ライトの出どころ
          shadow-bias={-0.0001} // シャドウのアーティファクトを防止
          intensity={isDark ? 0.5 : 0} // 明るさ
          angle={Math.PI / 2} // ライトの広がり具合
          penumbra={0.2} // ライトの中心から縁への減衰具合
          distance={0.4} // ライトの届く距離
          color="#d5d5d5"
          onUpdate={(self) => {
            self.target.position.set(0.12, 0.185, 0); // 照らしたい座標（机）
            self.target.updateMatrixWorld(); // 向きを即座に計算
          }}
        />
      </group>
      {/* sub_monitor */}
      <group position={[-1.186, 1.18, -0.163]} rotation={[0.002, -0.49, 0.07]}>
        <mesh
          geometry={nodes.立方体049.geometry}
          material={materials["light blue"]}
        />
        <mesh
          geometry={nodes.立方体049_1.geometry}
          material={materials.white}
        />
        <mesh
          geometry={nodes.立方体049_2.geometry}
          material={materials.silber}
        />
        <group position={[0.027, 0.08, 0]} rotation={[0, Math.PI / 2, 0]}>
          <MonitorContent
            monitorId={1}
            width={0.61} // 3. 赤い板が左右にはみ出ないかチェック
            height={0.36} // 4. 赤い板が上下にはみ出ないかチェック
          />
        </group>
        <spotLight
          position={[0.027, 0.08, 0]} // ライトの出どころ
          shadow-bias={-0.0001} // シャドウのアーティファクトを防止
          intensity={isDark ? 0.5 : 0}
          angle={Math.PI / 2} // ライトの広がり具合
          penumbra={0.2} // ライトの中心から縁への減衰具合
          distance={0.4} // ライトの届く距離
          color="#d5d5d5"
          onUpdate={(self) => {
            self.target.position.set(0.077, 0.08, 0); // 照らしたい座標（机）
            self.target.updateMatrixWorld(); // 向きを即座に計算
          }}
        />
      </group>
      {/* pc */}
      <group position={[-0.7, 0.7, -0.1]}>
        <group position={[0.7, -0.7, 0.1]}>
          {/* pc_main */}
          <group
            position={[-1.244, 0.279, -0.629]}
            rotation={[1.564, -1.568, 1.578]}
          >
            <mesh
              geometry={nodes.立方体007_1.geometry}
              material={materials.blue}
            />
            <mesh
              geometry={nodes.立方体007_2.geometry}
              material={materials.black}
            />
            <mesh
              geometry={nodes.立方体007_3.geometry}
              material={materials.white}
            />
            <mesh
              geometry={nodes.立方体007_4.geometry}
              material={materials.orange}
            />
            <mesh geometry={nodes.立方体007_5.geometry}>
              <meshStandardMaterial map={pcTexture} />
            </mesh>
            <mesh
              geometry={nodes.立方体007_6.geometry}
              material={materials.silber}
            />
            <mesh geometry={nodes.立方体007_7.geometry}>
              <meshStandardMaterial map={pcTexture} />
            </mesh>
            <mesh geometry={nodes.立方体007_8.geometry}>
              <meshStandardMaterial map={pcTexture} />
            </mesh>
            <pointLight
              intensity={isDark ? 0.2 : 0}
              distance={0.3}
              decay={2}
            ></pointLight>
          </group>
          {/* pc_glass */}
          <mesh
            geometry={nodes.pc_glass.geometry}
            // material={materials["pc glass"]}
            position={[-1.244, 0.279, -0.629]}
            rotation={[1.564, -1.568, 1.578]}
          >
            <meshPhysicalMaterial
              transparent={true}
              transmission={0.9} // 1.0で完全に光を通す（ガラス化）
              roughness={0.05} // 0に近いほどツルツル、少し上げるとマットな質感
              ior={1.5} // 屈折率。ガラスなら1.5前後がリアル
              thickness={0.5} // ガラスの厚み。屈折の見え方が変わります
              specularIntensity={1.0} // 反射の強さ
              envMapIntensity={1.5} // 周囲の景色の映り込みの強さ
              opacity={0.15} // 表面のうっすらとした色味
              color="#ffffff" // 少し青みがかった白にしてもエモい
            />
          </mesh>
        </group>
      </group>
      {/* mirror */}
      <group
        position={[-1.033, 0.844, -1.167]}
        rotation={[-0.393, 0.887, -2.831]}
      >
        <mesh geometry={nodes.立方体055.geometry} material={materials.brown} />
        <mesh
          geometry={nodes.立方体055_1.geometry}
          material={materials.white}
        />
      </group>
      {/* runba */}
      <group position={[-0.208, 0.078, -1.177]}>
        <mesh geometry={nodes.円柱028.geometry} material={materials.white} />
        <mesh geometry={nodes.円柱028_1.geometry} material={materials.silber} />
        <mesh geometry={nodes.円柱028_2.geometry} material={materials.black} />
      </group>
      {/* shelf_items */}
      <group position={[0.41, 0.567, -1.125]}>
        <mesh geometry={nodes.立方体059.geometry} material={materials.silber} />
        <mesh
          geometry={nodes.立方体059_1.geometry}
          material={materials["light blue"]}
        />
        <mesh
          geometry={nodes.立方体059_2.geometry}
          material={materials.white}
        />
        <mesh
          geometry={nodes.立方体059_3.geometry}
          material={materials.black}
        />
        <mesh
          geometry={nodes.立方体059_4.geometry}
          material={materials.brown}
        />
      </group>
      {/* record */}
      <group position={[1.3, 1.5, 0]}>
        <group position={[-1.3, -1.5, 0]}>
          {/* record_main */}
          <group position={[0.424, 1.105, -1.162]}>
            <mesh
              geometry={nodes.円柱019.geometry}
              material={materials.white}
            />
            <mesh
              geometry={nodes.円柱019_1.geometry}
              material={materials["light blue"]}
            />
            <mesh
              geometry={nodes.円柱019_2.geometry}
              material={materials.black}
            />
          </group>
          {/* record_detail_off */}
          {/* record_detail_on */}
          <group
            position={[0.527, 1.113, -1.19]}
            rotation={[1.566, -0.063, 0.597]}
            visible={!isDark}
          >
            <mesh geometry={nodes.円004.geometry} material={materials.silber} />
            <mesh
              geometry={nodes.円004_1.geometry}
              material={materials.orange}
            />
            <mesh
              geometry={nodes.円004_2.geometry}
              material={nodes.円004_2.material}
            />
          </group>
          <group visible={!isDark}>
            <MusicParticles />
          </group>

          <group
            position={[0.58, 1.115, -1.166]}
            visible={isDark} // ここで出し分け！
          >
            <mesh
              geometry={nodes.円002.geometry}
              material={nodes.円002.material}
            />
            <mesh
              geometry={nodes.円002_1.geometry}
              material={materials.silber}
            />
            <mesh
              geometry={nodes.円002_2.geometry}
              material={materials.orange}
            />
          </group>
        </group>
      </group>
      {/* bed_main */}
      <group position={[1.482, 0.536, -0.819]} rotation={[0, 0, -1.571]}>
        <mesh geometry={nodes.立方体058.geometry} material={materials.white} />
        <mesh
          geometry={nodes.立方体058_1.geometry}
          material={materials.silber}
        />
        <mesh geometry={nodes.立方体058_2.geometry} material={materials.blue} />
      </group>
      {/* bed_detail_on */}
      {/* bed_detail_off */}
      <mesh
        geometry={nodes.bedOn.geometry}
        material={materials["light blue"]}
        position={[1.989, 0.533, -0.62]}
        visible={isDark}
      />
      <mesh
        geometry={nodes.bedOff.geometry}
        material={materials["light blue"]}
        position={[1.592, 0.569, -0.822]}
        visible={!isDark}
      />
      {/* circle_carpet_gray */}
      <mesh
        geometry={nodes.carpet1.geometry}
        material={materials.silber}
        position={[1.498, 0.012, 0.505]}
      />
      {/* cushion_black */}
      <mesh
        geometry={nodes.cushion1.geometry}
        material={materials.black}
        position={[2.053, 0.06, 0.519]}
      />
      {/* cushion_blue */}
      <mesh
        geometry={nodes.cushion2.geometry}
        material={materials.blue}
        position={[2.069, 0.151, 0.804]}
        rotation={[0.521, 0.166, 0.015]}
      />
      {/* mini_desk */}
      <mesh
        geometry={nodes.desk.geometry}
        material={materials.brown}
        position={[1.137, 0.229, 0.642]}
      />
      {/* light */}
      <group position={[1.035, 0.579, 0.485]} rotation={[0, -0.448, 0.396]}>
        <mesh geometry={nodes.円柱011.geometry} material={materials.white} />
        <mesh geometry={nodes.円柱011_1.geometry} material={materials.brown} />
        <spotLight
          position={[0, -0.079, 0]} // ライトの出どころ
          shadow-bias={-0.0001} // シャドウのアーティファクトを防止
          intensity={isDark ? 1 : 0} // 明るさ
          angle={Math.PI / 3} // ライトの広がり具合
          penumbra={0.2} // ライトの中心から縁への減衰具合
          distance={0.4} // ライトの届く距離
          color="#d5d5d5"
          onUpdate={(self) => {
            self.target.position.set(1.137, 0.229, 0.642); // 照らしたい座標（机）
            self.target.updateMatrixWorld(); // 向きを即座に計算
          }}
        />
      </group>
      {/* rimo */}
      <group
        position={[1.147, 0.379, 0.812]}
        rotation={[-Math.PI, 1.242, -Math.PI]}
      >
        <mesh geometry={nodes.立方体019.geometry} material={materials.black} />
        <mesh
          geometry={nodes.立方体019_1.geometry}
          material={materials.silber}
        />
        <mesh
          geometry={nodes.立方体019_2.geometry}
          material={materials.white}
        />
        <mesh
          geometry={nodes.立方体019_3.geometry}
          material={materials.orange}
        />
        {/* 発光 */}
        <mesh position={[0, 0.002, -0.035]} rotation={[-Math.PI / 2, 0, 0]}>
          <planeGeometry args={[0.05, 0.035]} />
          <meshStandardMaterial
            color="#c0c0c0"
            emissive={"#cbcbcb"}
            emissiveIntensity={3}
            transparent
            side={THREE.DoubleSide}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/Room-draco.glb");
